# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rup}
  s.version = "0.3.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Hans-Gunther Schmidt"]
  s.date = %q{2009-10-15}
  s.default_executable = %q{rup}
  s.description = %q{Manage multiple SCM repositories at different locations of various types (SVN, GIT, REPO) with one simple CLI tool.}
  s.email = %q{hans@otype.de}
  s.executables = ["rup"]
  s.extra_rdoc_files = [
    "LICENSE"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "lib/rup.rb",
     "test/rup_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://rubyforge.org/projects/rup/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{rup}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{SCM Repository manager for SVN, GIT and REPO, made in Ruby}
  s.test_files = [
    "test/rup_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
